#!/bin/bash
#(1=vermelho; 2=verde; 3=amarelo; 4=azul; 5=roxo; 6=azul claro; 7=branco; 9=limpa)
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-10s\n' "COMANDOS DISPONÍVEIS:" ; tput sgr0 ; echo ""
tput setaf 2 ; tput bold ; printf '%s' "criarusuario " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Cria usuário com data de expiração e limite, mais ñ pronto para login por Chave Pública"
tput setaf 2 ; tput bold ; printf '%s' "apagar " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Apaga usuário, se tiver logado, use o comando: 'kill pid', onde 'pid' é um nº de processo do usuário" ;
tput setaf 2 ; tput bold ; printf '%s' "mudarsenha " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Muda a senha do usuário selecionado"
tput setaf 2 ; tput bold ; printf '%s' "mudardata " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Mudar a data de expiração de um usuário"
tput setaf 2 ; tput bold ; printf '%s' "mudarlimite " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Mudar conexões de usuarios criados com o comando: 'criarusuario'"
tput setaf 2 ; tput bold ; printf '%s' "monitor " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Verifica quem está conectado e quantos logins está usando"
tput setaf 2 ; tput bold ; printf '%s' "monitorar " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Monitora a quantidade de conexões simultâneas dos usuários"
tput setaf 2 ; tput bold ; printf '%s' "sshlimiter " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Limita as conexões de acordo com o limite dado a ele"
tput setaf 2 ; tput bold ; printf '%s' "addhost " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Adicionar domínio 'host' a lista de domínios permitidos no Proxy Squid"
tput setaf 2 ; tput bold ; printf '%s' "delhost " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Remover domínio 'host' da lista de domínios permitidos no Proxy Squid"
tput setaf 2 ; tput bold ; printf '%s' "velocidade " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Mede a taxa de download e mostra tabela de referencia de tempo de download"
tput setaf 2 ; tput bold ; printf '%s' "velocimetro " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Mede a navegação em Megabits (Mb), divida por 8 e terá a velocidade real"
tput setaf 2 ; tput bold ; printf '%s' "limpar " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Limpa a 'MEMÓRIA OCIOSA' mantendo o VPS mais rápido, ñ abuse deste comando"
tput setaf 2 ; tput bold ; printf '%s' "latencia " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Instala o TcpTweaker para tentar melhora o PING"
tput setaf 2 ; tput bold ; printf '%s' "badvpn " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Melhorar chamadas VoIp, VideoChamada e a velocidade de jogos online"
tput setaf 2 ; tput bold ; printf '%s' "relogio " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Configurar relogio do VPS, escolha sua cidade ou local com horário igual a vc, 'date' vê a hora"
tput setaf 2 ; tput bold ; printf '%s' "banner " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Cria o banner do VPS, depois de ditado: Ctrl+o e Ctrl+x para salvar"
tput setaf 5 ; tput bold ; printf '%s' "criar " ; tput setaf 1 ; printf '%s' "- " ; tput setaf 7 ; echo "Cria usuário com data de expiração e pronto para login via CHAVE PÚBLICA"
tput setaf 5 ; tput bold ; printf '%s' "detalhes " ; tput setaf 1 ; printf '%s' "- " ; tput setaf 7 ; echo "Mostra nome, senha, data e logins dos criados com comando: 'criar'"
tput setaf 2 ; tput bold ; printf '%s' "apps " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 6 ; echo "Como configurar os aplicativos Injector, Eproxy e Kpn" ; echo ""
tput sgr0
