#!/bin/bash
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-10s\n' "Como configurar os aplicativos:" ; tput sgr0 ; echo ""
tput setaf 2 ; tput bold ; printf '%s' "HTTP Injector, eProxy, KPN Tunnel, KPNTunnel Ultimate " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Mesma configuração para todos" ; echo ""
tput setaf 2 ; tput bold ; printf '%s' "CONTA SSH & PROXY: " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "IP_VPS & IP_VPS:Porta_operadora respectivamente" ; echo ""
tput setaf 2 ; tput bold ; printf '%s' "PORTA SSH: " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "443" ; echo ""
tput setaf 2 ; tput bold ; printf '%s' "USUÁRIO & SENHA: " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Usuário criado e senha definida para ele" ; echo ""
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-10s\n' "Portas do Proxy e PayLoads (texto de conexão) das operadoras:" ; tput sgr0 ; echo ""
tput setaf 2 ; tput bold ; printf '%s' "Claro: " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Porta do proxy: 80, 8080, 8799" ; echo "GET http://www.clarosync.com/ HTTP/1.1[cr][lf] [crlf][crlf][netData][cr][lf] [lf][lf]" ; echo ""
tput setaf 2 ; tput bold ; printf '%s' "vivo: " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Porta do proxy: 80" ; echo "[method] [host_port]@sdp.vivo.com.br [protocol]@NetGratisMobileE[crlf][crlf]" ; echo ""
tput setaf 2 ; tput bold ; printf '%s' "Tim: " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Porta do proxy: 80"; echo "[netData][crlf][split]GET http://tim.anti-theft.kaspersky.com/[protocol][crlf][crlf]" ; echo ""
tput setaf 2 ; tput bold ; printf '%s' "Oi: " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Porta do proxy: 3128" ; echo "[method] [host_port]@www.rdio.com/rewrite.pandora.com [protocol][crlf][crlf]" ; echo ""
tput setaf 4 ; tput bold ; printf '%s' "LOGIN SEGURO " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 5 ; echo "Login sem a SENHA de USUÁRIO, comando 'ajuda' para mais informações" ; echo ""
tput sgr0
