#!/bin/bash
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' " FireWall resete by @FranciscoManim " ; tput sgr0
tput setaf 3 ; tput bold ; echo "" ; echo "  Este script irá fazer no Debian, Ubuntu e CentOS:  " ; echo ""
echo "● Liberar: TORRENT e ataques Sniffer e Ddos" ; tput sgr0
echo ""
tput setaf 6 ; tput bold ; read -n 1 -s -p " Aperte qualquer tecla para continuar... " ; echo "" ; echo "" ; tput sgr0
tput setaf 7 ; tput setab 4 ; tput bold ; echo "  Resetando FireWall por motivo de conflitos...   " ; echo "" ; tput sgr0
echo ""
sleep 1
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
echo -e "\033[1;36mFireWall toralmente resetado:
FireWall INPUT Aceitando tudo
FireWall FORWARD Aceitando tudo
FireWall OUTPUT Aceitando tudo
Caso esteja arrependido de resetar a proteção,
Reconfigure o FireWall no COMANDO: FireWallblok\033[0m"
echo ""
