#!/bin/bash
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' " Bloqueio de Torrent by @FranciscoManim " ; tput sgr0
tput setaf 3 ; tput bold ; echo "" ; echo "  Este script irá fazer no Debian, Ubuntu e CentOS:  " ; echo ""
echo "● Bloquear TORRENT e ataques Sniffer e Ddos" ; tput sgr0
echo ""
tput setaf 6 ; tput bold ; read -n 1 -s -p "Aperte qualquer tecla para continuar..." ; echo "" ; echo "" ; tput sgr0
IP=$(wget -qO- ipv4.icanhazip.com)
read -p " Para continuar confirme se este é o IP do seu servidor: " -e -i $IP ipdovps
if [ -z "$ipdovps" ]
then
	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "" ; echo " IP deste servidor está errado. Tente novamente. " ; echo "" ; echo "" ; tput sgr0
	exit 1
fi
tput setaf 7 ; tput setab 4 ; tput bold ; echo "  Resetando FireWall para não haver conflitos...   " ; echo "" ; tput sgr0
echo ""
sleep 1
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
tput setaf 7 ; tput setab 4 ; tput bold ; echo "   Aguarde a RÁPIDA configuração automática   " ; echo "" ; tput sgr0
sleep 1
echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT
iptables -N syn-chain
iptables -N LOGDROP > /dev/null 2> /dev/null
iptables -F LOGDROP 
iptables -A LOGDROP -j LOG --log-prefix "LOGDROP "
iptables -A LOGDROP -j DROP
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -p icmp --icmp-type echo-request -j DROP
iptables -A FORWARD -m string --algo bm --string "Torrent" -j DROP
iptables -A FORWARD -m string --algo bm --string "torrent" --to 65535 -j DROP
iptables -A FORWARD -m string --algo bm --string ".torrent" --to 65535 -j DROP
iptables -A FORWARD -m string --algo bm --string ".torrent" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "torrent" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "announce" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "announce.php?passkey=" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "announce.php?passkey=" --to 65535 -j DROP
iptables -A FORWARD -m string --algo bm --string "announce" --to 65535 -j DROP
iptables -A FORWARD -m string --algo bm --string "announce_peer" --to 65535 -j DROP
iptables -A FORWARD -m string --string "announce_peer" --algo bm -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "peer_id=" --to 65535 -j DROP
iptables -A FORWARD -m string --algo bm --string "peer_id=" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "info_hash" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "info_hash" --to 65535 -j DROP
iptables -A FORWARD -m string --algo bm --string "get_peers" --to 65535 -j DROP
iptables -A FORWARD -m string --string "get_peers" --algo bm -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "find_node" --to 65535 -j DROP
iptables -A FORWARD -m string --string "find_node" --algo bm -j LOGDROP
iptables -A FORWARD -p tcp --dport 6881:6889 -j DROP
iptables -A FORWARD -p udp --dport 1024:65534 -j DROP
iptables -A FORWARD -s $ipdovps/24 -p tcp -m tcp --sport 1024:65535 --dport 1024:65535 -j REJECT --reject-with icmp-port-unreachable
iptables -A FORWARD -s $ipdovps/24 -p udp -m udp --sport 1024:65535 --dport 1024:65535 -j REJECT --reject-with icmp-port-unreachable
iptables -A INPUT -p tcp --destination-port 6881:6999 -j DROP
iptables -A INPUT -p icmp --icmp-type echo-reply -m limit --limit 1/s -j DROP
iptables -A OUTPUT -p tcp --source-port 6881:6999 -j DROP
iptables -A FORWARD -m string --algo bm --string "BitTorrent" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "BitTorrent" -j DROP
iptables -A FORWARD -m string --algo bm --string "BitTorrent protocol" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "BitTorrent" --to 65535 -j DROP
iptables -A FORWARD -m string --algo bm --string "BitTorrent protocol" --to 65535 -j DROP
iptables -A FORWARD -p tcp -i eth0 --dport 6881:6889 -d $ipdovps -j REJECT
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 6881:6889 -j DNAT --to-dest $ipdovps
# ARES bloquear
iptables -A FORWARD -m string --algo bm --string "ares" -j DROP
# IMESH BLOQUEAR:
iptables -A FORWARD -d 216.35.208.0/24 -j REJECT
# BearShare e ToadNode BLOQUEAR:
iptables -A FORWARD -p TCP --dport 6346 -j REJECT
# WinMX BLOQUEAR:
iptables -A FORWARD -d 209.61.186.0/24 -j REJECT
iptables -A FORWARD -d 64.49.201.0/24 -j REJECT
# Napigator BLOQUEAR:
iptables -A FORWARD -d 209.25.178.0/24 -j REJECT
# Morpheus BLOQUEAR:
iptables -A FORWARD -d 206.142.53.0/24 -j REJECT
iptables -A FORWARD -p TCP --dport 1214 -j REJECT
# KaZaA BLOQUEAR:
iptables -A FORWARD -d 213.248.112.0/24 -j REJECT
iptables -A FORWARD -p TCP --dport 1214 -j REJECT
# Limewire BLOQUEAR:
iptables -A FORWARD -p TCP --dport 6346 -j REJECT
# Audiogalaxy BLOQUEAR:
iptables -A FORWARD -d 64.245.58.0/23 -j REJECT
# ----FIM DO SCRIPT DE BLOQUEIO DE TORRET------
# Ping da morte
iptables -t filter -A syn-chain -p tcp --syn -m limit --limit 2/s -j ACCEPT
iptables -A INPUT -p tcp --syn -s 127.0.0.1 -j ACCEPT
iptables -A INPUT -p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT
# PROXY TRANSPARENTE
iptables -t nat -A PREROUTING -s $ipdovps/255.255.255.0 -p tcp --dport 80 -j REDIRECT --to-port 3128
iptables -t nat -A POSTROUTING -s $ipdovps/255.255.255.0 -o eth0 -j MASQUERADE
# Liberando tunelamento SSH
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -t filter -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
# Liberar navegação TCP
iptables -A FORWARD -p tcp --dport 3389 -d $ipdovps -j ACCEPT
# Ntop monitor de redes
iptables -A FORWARD -p tcp --dport 3000 -d $ipdovps -j ACCEPT
# SSH liberando login no VPS
iptables -A FORWARD -p tcp --dport 22 -d $ipdovps -j ACCEPT
iptables -A FORWARD -p tcp --dport 4789 -d $ipdovps -j ACCEPT
# Liberar jogos online
iptables -t nat -A PREROUTING -i eth0 -p udp --dport 7777:7779 -j DNAT --to-dest $ipdovps
iptables -A FORWARD -p udp -i eth0 --dport 7777:7779 -d $ipdovps -j ACCEPT
# LIBERANDO portas gerais Chain INPUT
iptables -A INPUT -p tcp --dport 22 -i eth0 -j ACCEPT
iptables -A INPUT -p tcp --dport 4789 -i eth0 -j ACCEPT
iptables -A INPUT -p tcp --dport 443 -i eth0 -j ACCEPT
iptables -A INPUT -p tcp --dport 3000 -i eth0 -j ACCEPT
iptables -A INPUT -p tcp --dport 8080 -i eth0 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -i eth0 -j ACCEPT
iptables -A INPUT -p tcp --dport 3128 -i eth0 -j ACCEPT
iptables -A INPUT -p tcp --dport 8799 -i eth0 -j ACCEPT
iptables -A INPUT -p tcp --dport 2223 -i eth0 -j ACCEPT
# LIBERANDO portas gerais Chain OUTPUT
iptables -A OUTPUT -p tcp --dport 22 -o eth0 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 4789 -o eth0 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -o eth0 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8080 -o eth0 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -o eth0 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 3128 -o eth0 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8799 -o eth0 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 53 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -p tcp --dport 67 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -p udp --dport 67 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -p tcp -d $ipdovps --dport 443 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -p tcp -d $ipdovps --dport 80 -m state --state NEW -j ACCEPT
# LIBERANDO portas gerais Chain FORWARD
iptables -A FORWARD -p tcp --dport 8080 -i eth0 -j ACCEPT
iptables -A FORWARD -p tcp --dport 4789 -i eth0 -j ACCEPT
iptables -A FORWARD -p tcp --dport 80 -i eth0 -j ACCEPT
iptables -A FORWARD -p tcp --dport 3128 -i eth0 -j ACCEPT
iptables -A FORWARD -p tcp --dport 8799 -i eth0 -j ACCEPT
echo -e "\033[1;36mFireWall toralmente configurado:
Portas 443 22 80 8080 8799 3128 liberadas
Bloqueados: ICMP Torrent e ataque DDoS
Caso esteja dando problemas no servidor,
resete o FireWall no COMANDO: FireWallsafe\033[0m"
echo ""
