#!/bin/bash
tput setaf 1 ; tput setab 2 ; tput bold ; printf '%35s%s%-20s\n' "Gerenciador de VPS ManimEdicoes Telegram: @FranciscoManim" ; tput sgr0
tput setaf 4 ; tput bold ; echo "" ; echo "Este script de VPS irá:" ; echo ""
echo "● Instalar e configurar o proxy squid nas portas 80, 3128" ; echo "  para permitir conexões SSH para este servidor"
echo "● Configurar o OpenSSH para rodar nas portas 22 e 443"
echo "● Configurar o squid para AUTOLIMPAR o cache deixando-o mais rápido"
echo "● Configurar o log de acesso para monitoração de sites acessados."
echo "● Instalar um conjunto de COMANDOS para facilitar ; echo " o gerenciamento de usuários e da VPS" ; tput sgr0
echo ""
tput setaf 3 ; tput bold ; read -n 1 -s -p "Aperte qualquer tecla para continuar..." ; echo "" ; echo "" ; tput sgr0
IP=$(wget -qO- ipv4.icanhazip.com)
read -p "Para continuar confirme se este é o IP do seu servidor: " -e -i $IP ipdovps
if [ -z "$ipdovps" ]
then
	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "" ; echo " IP deste servidor está errado. Tente novamente. " ; echo "" ; echo "" ; tput sgr0
	exit 1
fi
if [ -f "/root/usuarios.db" ]
then
tput setaf 6 ; tput bold ;	echo ""
	echo "Uma base de dados de usuários ('usuarios.db') foi encontrada!"
	echo "Deseja mantê-la (preservando o limite de conexões dos usuários)"
	echo "ou criar uma nova base de dados?"
	tput setaf 6 ; tput bold ;	echo ""
	echo "[1] Manter Base de Dados Atual, ela não sofrerá mudanças."
	echo "[2] Criar uma Nova Base de Dados, apagará tudo da antiga."
	echo "" ; tput sgr0
	read -p "Opção?: " -e -i 1 optiondb
else
	awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > /root/usuarios.db
fi
echo ""
read -p "Ativar a compressão SSH (há ganho de performance em servidores acessados via internet)? [s/n]) " -e -i n sshcompression
echo ""
tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Aguarde a configuração automática" ; echo "" ; tput sgr0
sleep 3
apt-get update -y
rm /bin/criarusuario /bin/expcleaner /bin/sshlimiter /bin/addhost /bin/listar /bin/sshmonitor /bin/ajuda  /bin/detalhes /bin/delhost /bin/criar /bin/apagar /bin/mudardata /bin/limitador /bin/limpar /bin/monitor /bin/mudarsenha /bin/velocimetro /bin/velocimetro-cgi > /dev/null
rm /root/ExpCleaner.sh /root/CriarUsuario.sh /root/sshlimiter.sh > /dev/null
apt-get install squid3 bc screen nano unzip dos2unix wget -y
killall apache2
apt-get purge apache2 -y
if [ -f "/usr/sbin/ufw" ] ; then
	ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ;
fi
if [ -d "/etc/squid3/" ]
then
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/squid1 -O /tmp/sqd1
	echo "acl url3 dstdomain -i $ipdovps" > /tmp/sqd2
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/squid2 -O /tmp/sqd3
	cat /tmp/sqd1 /tmp/sqd2 /tmp/sqd3 > /etc/squid3/squid.conf
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/payload -O /etc/squid3/payload.txt
	echo " " >> /etc/squid3/payload.txt
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/sites_bloqueados -O /etc/squid3/sites_bloqueados.txt
	echo " " >> /etc/squid3/sites_bloqueados.txt
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/formato_arquivo -O /etc/squid3/formato_arquivo.txt
	echo " " >> /etc/squid3/formato_arquivo.txt
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/access.log -O /var/log/squid3/access.log
	echo " " >> /var/log/squid3/access.log
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/squid3.pid -O /var/log/squid3/squid3.pid
	echo " " >> /var/log/squid3/squid3.pid
	grep -v "^Port 443" /etc/ssh/sshd_config > /tmp/ssh && mv /tmp/ssh /etc/ssh/sshd_config
	echo "Port 443" >> /etc/ssh/sshd_config
	grep -v "^PasswordAuthentication yes" /etc/ssh/sshd_config > /tmp/passlogin && mv /tmp/passlogin /etc/ssh/sshd_config
	echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/addhost -O /bin/addhost
	chmod +x /bin/addhost
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/criar -O /bin/criar
	chmod +x /bin/criar
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/detalhes -O /bin/detalhes
	chmod +x /bin/detalhes
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/mudardata -O /bin/mudardata
	chmod +x /bin/mudardata
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/limitador -O /bin/limitador
	chmod +x /bin/limitador
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/limpar -O /bin/limpar
	chmod +x /bin/limpar
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/monitor -O /bin/monitor
	chmod +x /bin/monitor
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/mudarsenha -O /bin/mudarsenha
	chmod +x /bin/mudarsenha
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/delhost -O /bin/delhost
	chmod +x /bin/delhost
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/apagar -O /bin/apagar
	chmod +x /bin/apagar
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/velocimetro -O /bin/velocimetro
	chmod +x /bin/velocimetro
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/velocimetro-cgi -O /bin/velocimetro-cgi
	chmod +x /bin/velocimetro-cgi
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/ajuda -O /bin/ajuda
	chmod +x /bin/ajuda
	if [ ! -f "/etc/init.d/squid3" ]
	then
		service squid3 reload > /dev/null
	else
		/etc/init.d/squid3 reload > /dev/null
	fi
	if [ ! -f "/etc/init.d/ssh" ]
	then
		service ssh reload > /dev/null
	else
		/etc/init.d/ssh reload > /dev/null
	fi
fi
if [ -d "/etc/squid/" ]
then
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/squid1 -O /tmp/sqd1
	echo "acl url3 dstdomain -i $ipdovps" > /tmp/sqd2
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/squid2 -O /tmp/sqd3
	cat /tmp/sqd1 /tmp/sqd2 /tmp/sqd3 > /etc/squid3/squid.conf
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/payload -O /etc/squid3/payload.txt
	echo " " >> /etc/squid3/payload.txt
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/sites_bloqueados -O /etc/squid3/sites_bloqueados.txt
	echo " " >> /etc/squid3/sites_bloqueados.txt
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/formato_arquivo -O /etc/squid3/formato_arquivo.txt
	echo " " >> /etc/squid3/formato_arquivo.txt
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/access.log -O /var/log/squid3/access.log
	echo " " >> /var/log/squid3/access.log
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/squid3.pid -O /var/log/squid3/squid3.pid
	echo " " >> /var/log/squid3/squid3.pid
	grep -v "^Port 443" /etc/ssh/sshd_config > /tmp/ssh && mv /tmp/ssh /etc/ssh/sshd_config
	echo "Port 443" >> /etc/ssh/sshd_config
	grep -v "^PasswordAuthentication yes" /etc/ssh/sshd_config > /tmp/passlogin && mv /tmp/passlogin /etc/ssh/sshd_config
	echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/addhost -O /bin/addhost
	chmod +x /bin/addhost
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/criar -O /bin/criar
	chmod +x /bin/criar
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/detalhes -O /bin/detalhes
	chmod +x /bin/detalhes
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/mudardata -O /bin/mudardata
	chmod +x /bin/mudardata
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/limitador -O /bin/limitador
	chmod +x /bin/limitador
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/limpar -O /bin/limpar
	chmod +x /bin/limpar
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/monitor -O /bin/monitor
	chmod +x /bin/monitor
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/mudarsenha -O /bin/mudarsenha
	chmod +x /bin/mudarsenha
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/delhost -O /bin/delhost
	chmod +x /bin/delhost
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/apagar -O /bin/apagar
	chmod +x /bin/apagar
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/velocimetro -O /bin/velocimetro
	chmod +x /bin/velocimetro
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/velocimetro-cgi -O /bin/velocimetro-cgi
	chmod +x /bin/velocimetro-cgi
	wget https://raw.githubusercontent.com/manimedicoes/GerenciadorVPS/master/ajuda -O /bin/ajuda
	chmod +x /bin/ajuda
	if [ ! -f "/etc/init.d/squid3" ]
	then
		service squid reload > /dev/null
	else
		/etc/init.d/squid reload > /dev/null
	fi
	if [ ! -f "/etc/init.d/ssh" ]
	then
		service ssh reload > /dev/null
	else
		/etc/init.d/ssh reload > /dev/null
	fi
fi
echo ""
tput setaf 7 ; tput setab 4 ; tput bold ; echo "Proxy Squid Instalado e rodando nas portas: 80, 3128" ; tput sgr0
tput setaf 7 ; tput setab 4 ; tput bold ; echo "OpenSSH rodando nas portas 22 e 443" ; tput sgr0
tput setaf 7 ; tput setab 4 ; tput bold ; echo "Scripts para gerenciamento de usuário instalados" ; tput sgr0
tput setaf 7 ; tput setab 4 ; tput bold ; echo "Para ver os COMANDOS DISPONÍVEIS use o comando: ajuda" ; tput sgr0
echo ""
if [[ "$optiondb" = '2' ]]; then
	awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > /root/usuarios.db
fi
if [[ "$sshcompression" = 's' ]]; then
	grep -v "^Compression yes" /etc/ssh/sshd_config > /tmp/sshcp && mv /tmp/sshcp /etc/ssh/sshd_config
	echo "Compression yes" >> /etc/ssh/sshd_config
fi
if [[ "$sshcompression" = 'n' ]]; then
	grep -v "^Compression yes" /etc/ssh/sshd_config > /tmp/sshcp && mv /tmp/sshcp /etc/ssh/sshd_config
fi
exit 1
