#!/bin/bash
formato_arquivo="/etc/squid3/formato_arquivo.txt"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-10s\n' "Liberar Mídia para download" ; tput sgr0
if [ ! -f "$formato_arquivo" ]
then
	tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Arquivo $formato_arquivo não encontrado" ; tput sgr0
	exit 1
else
	tput setaf 2 ; tput bold ; echo ""; echo "Midias atuais bloqueadas para download $formato_arquivo:" ; tput sgr0
	tput setaf 3 ; tput bold ; echo "" ; cat $formato_arquivo ; echo "" ; tput sgr0
	read -p "Digite a extensão que deseja liberar o download: " midia
	if [[ -z $midia ]]
		then
			tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Você digitou uma extensão não existente!" ; echo "" ; tput sgr0
			exit 1
		else
		if [[ `grep -c "^$midia" $formato_arquivo` -ne 1 ]]
		then
			tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "A extensão $midia não foi encontrada no arquivo $formato_arquivo" ; echo "" ; tput sgr0
			exit 1
		else
			grep -v "^$midia" $formato_arquivo > /tmp/a && mv /tmp/a $formato_arquivo
			tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Arquivo $formato_arquivo atualizado, a midia foi liberada para download:" ; tput sgr0
			tput setaf 3 ; tput bold ; echo "" ; cat $formato_arquivo ; echo "" ; tput sgr0
			if [ ! -f "/etc/init.d/squid3" ]
			then
				service squid3 reload
			else
				/etc/init.d/squid3 reload
			fi	
			tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Arquivos com esta extensão estão liberados para download!" ; echo "" ; tput sgr0
			exit 1
		fi
	fi
fi
