#!/bin/bash
# (1=vermelho; 2=verde; 3=amarelo; 4=azul; 5=roxo; 6=azul claro; 7=branco; 9=limpa)
formato_arquivo="/etc/squid3/formato_arquivo.txt"
tput setaf 4 ; tput setab 7 ; tput bold ; printf '%35s%s%-10s\n' "Bloquear download de Mídias" ; tput sgr0
if [ ! -f "$formato_arquivo" ]
then
	tput setaf 1 ; tput setab 2 ; tput bold ; echo "" ; echo "Arquivo $formato_arquivo não encontrado" ; tput sgr0
	exit 1
else
	tput setaf 5 ; tput bold ; echo ""; echo "Mídias atuais bloqueadas para download $formato_arquivo:" ; tput sgr0
	tput setaf 2 ; tput bold ; echo "" ; cat $formato_arquivo ; echo "" ; tput sgr0
	read -p "Digite a extensão da midia que deseja Bloquear |ex: .extensão|: " midia
	if [[ -z $midia ]]
	then
		tput setaf 5 ; tput setab 7 ; tput bold ; echo "" ; echo "Você digitou uma extensão não existente!" ; echo "" ; tput sgr0
		exit 1
	else
		if [[ `grep -c "^$midia" $formato_arquivo` -eq 1 ]]
		then
			tput setaf 5 ; tput setab 7 ; tput bold ; echo "" ; echo "A midia $midia já existe no arquivo $formato_arquivo" ; echo "" ; tput sgr0
			exit 1
		else
			if [[ $midia != \.* ]]
			then
				tput setaf 5 ; tput setab 7 ; tput bold ; echo "" ; echo "Você deve Bloquear uma extensão de midia iniciando-a com um ponto!" ; echo "Por exemplo: .mp3" ; echo ""; tput sgr0
				exit 1
			else
				echo "$midia" >> $formato_arquivo && grep -v "^$" $formato_arquivo > /tmp/a && mv /tmp/a $formato_arquivo
				tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Arquivo $formato_arquivo atualizado, a extensão de midia foi adicionada com sucesso:" ; tput sgr0
				tput setaf 4 ; tput bold ; echo "" ; cat $formato_arquivo ; echo "" ; tput sgr0
				if [ ! -f "/etc/init.d/squid3" ]
				then
					service squid3 reload
				else
					/etc/init.d/squid3 reload
				fi	
				tput setaf 2 ; tput setab 4 ; tput bold ; echo "" ; echo "Arquivos com esta extensão estão bloqueados para download!" ; echo "" ; tput sgr0
				exit 1
			fi
		fi
	fi
fi
