#!/bin/bash
sites_bloqueados="/etc/squid3/sites_bloqueados.txt"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-10s\n' "Liberar sites para navegação" ; tput sgr0
if [ ! -f "$sites_bloqueados" ]
then
	tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Arquivo $sites_bloqueados não encontrado" ; tput sgr0
	exit 1
else
	tput setaf 2 ; tput bold ; echo ""; echo "Dominios atuais bloqueadas para navegação $sites_bloqueados:" ; tput sgr0
	tput setaf 3 ; tput bold ; echo "" ; cat $sites_bloqueados ; echo "" ; tput sgr0
	read -p "Digite o domínio que deseja liberar a navegação: " site
	if [[ -z $site ]]
		then
			tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Você digitou um domínio não existente!" ; echo "" ; tput sgr0
			exit 1
		else
		if [[ `grep -c "^$site" $sites_bloqueados` -ne 1 ]]
		then
			tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "O domínio $site não foi encontrado no arquivo $sites_bloqueados" ; echo "" ; tput sgr0
			exit 1
		else
			grep -v "^$site" $sites_bloqueados > /tmp/a && mv /tmp/a $sites_bloqueados
			tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Arquivo $sites_bloqueados atualizado, os sites com este domínio estão liberados para navegação:" ; tput sgr0
			tput setaf 3 ; tput bold ; echo "" ; cat $sites_bloqueados ; echo "" ; tput sgr0
			if [ ! -f "/etc/init.d/squid3" ]
			then
				service squid3 reload
			else
				/etc/init.d/squid3 reload
			fi	
			tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Sites com este domínio não serão mais bloqueados para navegação!" ; echo "" ; tput sgr0
			exit 1
		fi
	fi
fi
