#!/bin/bash
# (1=vermelho; 2=verde; 3=amarelo; 4=azul; 5=roxo; 6=azul claro; 7=branco; 9=limpa)
sites_bloqueados="/etc/squid3/sites_bloqueados.txt"
tput setaf 4 ; tput setab 7 ; tput bold ; printf '%35s%s%-10s\n' "Bloquear Sites proibidos e perigosos" ; tput sgr0
if [ ! -f "$sites_bloqueados" ]
then
	tput setaf 1 ; tput setab 2 ; tput bold ; echo "" ; echo "Arquivo $sites_bloqueados não encontrado" ; tput sgr0
	exit 1
else
	tput setaf 5 ; tput bold ; echo ""; echo "Sites atuais bloqueados $sites_bloqueados:" ; tput sgr0
	tput setaf 2 ; tput bold ; echo "" ; cat $sites_bloqueados ; echo "" ; tput sgr0
	read -p "Digite o DOMÍNIO do site que deseja Bloquear |ex: .facebook.com|: " site
	if [[ -z $site ]]
	then
		tput setaf 5 ; tput setab 7 ; tput bold ; echo "" ; echo "Você digitou um domínio não existente!" ; echo "" ; tput sgr0
		exit 1
	else
		if [[ `grep -c "^$site" $sites_bloqueados` -eq 1 ]]
		then
			tput setaf 5 ; tput setab 7 ; tput bold ; echo "" ; echo "O dominio $site já existe no arquivo $sites_bloqueados" ; echo "" ; tput sgr0
			exit 1
		else
			if [[ $site != \.* ]]
			then
				tput setaf 5 ; tput setab 7 ; tput bold ; echo "" ; echo "Você deve Bloquear um domínio de site iniciando-o com um ponto!" ; echo "Por exemplo: .facebook.com" ; echo ""; tput sgr0
				exit 1
			else
				echo "$site" >> $sites_bloqueados && grep -v "^$" $sites_bloqueados > /tmp/a && mv /tmp/a $sites_bloqueados
				tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Arquivo $sites_bloqueados atualizado, o dominio do site foi adicionada com sucesso:" ; tput sgr0
				tput setaf 4 ; tput bold ; echo "" ; cat $sites_bloqueados ; echo "" ; tput sgr0
				if [ ! -f "/etc/init.d/squid3" ]
				then
					service squid3 reload
				else
					/etc/init.d/squid3 reload
				fi	
				tput setaf 2 ; tput setab 4 ; tput bold ; echo "" ; echo "Sites com este domínio estão bloqueados para navegação!" ; echo "" ; tput sgr0
				exit 1
			fi
		fi
	fi
fi
