#!/bin/bash
tput setaf 1 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' "Bloqueando Torrent Telegram @FranciscoManim" ; tput sgr0
tput setaf 3 ; tput bold ; echo "" ; echo "Este script irá instalar no Debian, Ubuntu e CentOS:" ; echo ""
echo "● Bloquear TORRENT e SITES de invasões Sniffer" ; tput sgr0
echo ""
tput setaf 6 ; tput bold ; read -n 1 -s -p "Aperte qualquer tecla para continuar..." ; echo "" ; echo "" ; tput sgr0
IP=$(wget -qO- ipv4.icanhazip.com)
read -p "Para continuar confirme se este é o IP do seu servidor: " -e -i $IP ipdovps
if [ -z "$ipdovps" ]
then
	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "" ; echo " IP deste servidor está errado. Tente novamente. " ; echo "" ; echo "" ; tput sgr0
	exit 1
fi
tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Aguarde a configuração automática" ; echo "" ; tput sgr0
sleep 3
iptables -A FORWARD -m string --algo bm --string "Torrent" -j DROP
iptables -A FORWARD -m string --algo bm --string "torrent" --to 65535 -j DROP
iptables -A FORWARD -m string --algo bm --string ".torrent" --to 65535 -j DROP
iptables -A FORWARD -m string --algo bm --string ".torrent" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "torrent" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "announce" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "announce.php?passkey=" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "announce.php?passkey=" --to 65535 -j DROP
iptables -A FORWARD -m string --algo bm --string "announce" --to 65535 -j DROP
iptables -A FORWARD -m string --algo bm --string "announce_peer" --to 65535 -j DROP
iptables -A FORWARD -m string --string "announce_peer" --algo bm -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "peer_id=" --to 65535 -j DROP
iptables -A FORWARD -m string --algo bm --string "peer_id=" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "info_hash" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "info_hash" --to 65535 -j DROP
iptables -A FORWARD -m string --algo bm --string "get_peers" --to 65535 -j DROP
iptables -A FORWARD -m string --string "get_peers" --algo bm -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "find_node" --to 65535 -j DROP
iptables -A FORWARD -m string --string "find_node" --algo bm -j LOGDROP
iptables -A FORWARD -p tcp --dport 6881:6889 -j DROP
iptables -A FORWARD -p udp --dport 1024:65534 -j DROP
iptables -A FORWARD -s $IP/24 -p tcp -m tcp --sport 1024:65535 --dport 1024:65535 -j REJECT --reject-with icmp-port-unreachable
iptables -A FORWARD -s $IP/24 -p udp -m udp --sport 1024:65535 --dport 1024:65535 -j REJECT --reject-with icmp-port-unreachable
iptables -A INPUT -p tcp --destination-port 6881:6999 -j DROP
iptables -A INPUT -p icmp --icmp-type echo-reply -m limit --limit 1/s -j DROP
iptables -A OUTPUT -p tcp --source-port 6881:6999 -j DROP
iptables -A FORWARD -m string --algo bm --string "BitTorrent" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "BitTorrent" -j DROP
iptables -A FORWARD -m string --algo bm --string "BitTorrent protocol" -j LOGDROP
iptables -A FORWARD -m string --algo bm --string "BitTorrent" --to 65535 -j DROP
iptables -A FORWARD -m string --algo bm --string "BitTorrent protocol" --to 65535 -j DROP
iptables -A FORWARD -p tcp -i eth0 --dport 6881:6889 -d $IP -j REJECT
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 6881:6889 -j DNAT --to-dest $IP
# ARES bloquear
iptables -A FORWARD -m string --algo bm --string "ares" -j DROP
# IMESH BLOQUEAR:
iptables -A FORWARD -d 216.35.208.0/24 -j REJECT
# BearShare e ToadNode BLOQUEAR:
iptables -A FORWARD -p TCP --dport 6346 -j REJECT
# WinMX BLOQUEAR:
iptables -A FORWARD -d 209.61.186.0/24 -j REJECT
iptables -A FORWARD -d 64.49.201.0/24 -j REJECT
# Napigator BLOQUEAR:
iptables -A FORWARD -d 209.25.178.0/24 -j REJECT
# Morpheus BLOQUEAR:
iptables -A FORWARD -d 206.142.53.0/24 -j REJECT
iptables -A FORWARD -p TCP --dport 1214 -j REJECT
# KaZaA BLOQUEAR:
iptables -A FORWARD -d 213.248.112.0/24 -j REJECT
iptables -A FORWARD -p TCP --dport 1214 -j REJECT
# Limewire BLOQUEAR:
iptables -A FORWARD -p TCP --dport 6346 -j REJECT
# Audiogalaxy BLOQUEAR:
iptables -A FORWARD -d 64.245.58.0/23 -j REJECT
