#!/bin/bash
echo -e "\033[1;31mMedindo a velocidade...\033[0m"
ping=$(ping -c1 google.com |awk '{print $8 $9}' |grep -v loss |cut -d = -f2 |sed ':a;N;s/\n//g;ta')
echo "Ping: $ping"
velo=$(velocimetro.py |grep load:)
echo "$velo"
